fix: update community call information
IBM/compliance-trestle pull request #1444
Opened 2023-09-05 00:31 UTC by AleJo2995

## Types of changes

- [ ] Hot fix (emergency fix and release)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Documentation (change which affects the documentation site)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Release (`develop` -> `main`)

## Quality assurance (all should be covered).

- [x] My code follows the code style of this project.
- [x] Documentation for my change is up to date?
- [x] My PR meets testing requirements.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Summary

An easy update to community call information

## Key links:

- [Sonar coverage](https://sonarcloud.io/dashboard?id=compliance-trestle)

# Before you merge

- Ensure it is a 'squash commit' if not a release.
- Ensure CI is currently passing
- Check sonar. If you are working for a fork a maintainer will reach out, if required.

2023-09-05 04:26 UTC, vikas-agarwal76 approved these changes
LGTM

2023-09-20 18:13 UTC, mrgadgil requested changes

2023-09-20 18:13 UTC, mrgadgil commented on README.md
> +Hosted by Alejandro Leiva
Do you want to remove this line?

2023-09-20 18:27 UTC, AleJo2995 commented on README.md
> +Hosted by Alejandro Leiva
Done

2023-09-20 18:43 UTC, mrgadgil approved these changes

2023-09-20 18:44 UTC, merged