docs: Initial setup of documentation website.
IBM/compliance-trestle pull request #234
Opened 2020-11-23 02:46 UTC by butler54

Signed-off-by: Chris Butler <chris@thebutlers.me>

## Types of changes

- \[ \] Bug fix (non-breaking change which fixes an issue)
- \[ \] New feature (non-breaking change which adds functionality)
- \[ \] Breaking change (fix or feature that would cause existing functionality to change)
- \[x\] My code follows the code style of this project.
- \[x\] My change requires a change to the documentation.
- \[x\] I have updated the documentation accordingly.
- \[ \] I have added tests to cover my changes.
- \[x\] All new and existing tests passed.
- \[x\] All commits are signed.

This is an initial setup for a documentation website as described in #83. Given the complexity of our current build process I've chosen so far the simplest possible path - that is a github 'project page' (as opposed to an organizational page OR read the docs).

Note that some of the api docs will not be resolved correctly until the models are updated in #233 to produce the cleanest possible outcomes.

NOTE: Draft at this stage and expecting substantial feedback will be required to get this where we want it to be.

2021-01-12 10:04 UTC, butler54 commented
Ready for review.

2021-01-13 04:09 UTC, aNebula requested changes
We need a small change in the doc for `trestle merge` to take only -e instead of -f and -d. I will make changes in the spec through the #295 .

2021-01-14 13:53 UTC, aNebula commented on docs/cli.md
> +For example, in the command `trestle merge -e catalog.metadata`, executed in the same directory where `catalog.json` or splitted `catalog` directory exists, the property `metadata` from `metadata.jso
@butler54 Please review these and let me know if they make sense

2021-01-14 13:53 UTC, aNebula commented on docs/specifications/trestle-spec.md
> +For example, in the command `trestle merge -e catalog.metadata`, executed in the same directory where `catalog.json` or splitted `catalog` directory exists, the property `metadata` from `metadata.jso
@butler54 same changes here.

2021-01-14 23:13 UTC, aNebula approved these changes
LGTM

2021-01-14 23:14 UTC, merged