Trestle import and unit testing
IBM/compliance-trestle pull request #255
Opened 2020-12-07 13:12 UTC by jeffdmgit

## Types of changes

- \[ \] Bug fix (non-breaking change which fixes an issue)
- \[x\] New feature (non-breaking change which adds functionality)
- \[ \] Breaking change (fix or feature that would cause existing functionality to change)
- \[x\] My code follows the code style of this project.
- \[ \] My change requires a change to the documentation.
- \[ \] I have updated the documentation accordingly.
- \[x\] I have added tests to cover my changes.
- \[x\] All new and existing tests passed.
- \[ \] All commits are signed.

This closes #38.

2020-12-08 00:20 UTC, jeffdmgit commented
Failing import__test.py in Windows, it seems, when importing a target definition. Otherwise checks fine on Linux and MacOS, although macos-latest, 3.8 was cancelled, probably when the Windows checks failed.

2020-12-08 01:49 UTC, butler54 requested changes
The test suite is a bit messy and can be cleaned up. The code in the actual function looks pretty good (+- the error handling which is in the messages).

Once the test suite is a bit cleaner ping me and I can re-review.

2020-12-08 02:40 UTC, jeffdmgit commented on trestle/core/commands/import_.py
> +            pass
Fixed for all occurrences.

2020-12-08 02:48 UTC, jeffdmgit commented on trestle/core/commands/import_.py
> +            logger.error(f'Import failed (FileContentType.to_content_type()): {err}')
Provided clearer error logs. Retained references to internal classes in debug logs.

2020-12-08 02:49 UTC, jeffdmgit commented on trestle/core/commands/import_.py
> +            return 1
Ok. More thinking via issue #256 then.

2020-12-08 02:49 UTC, jeffdmgit commented on trestle/core/commands/import_.py
> +            plural_path = parent_alias + 's'
Handle via #256?

2020-12-08 05:13 UTC, jeffdmgit commented on tests/trestle/core/commands/import__test.py
> +                AssertionError()
Simplified with return code checking. No exceptions are raised on the import code being tested anyway.

2020-12-08 06:00 UTC, jeffdmgit commented on tests/trestle/core/commands/import__test.py
> +            assert rc == 1
Not quite following. I think we ought to let the full Trestle() class run lest we miss the initial args validations and what not.

2020-12-08 06:01 UTC, jeffdmgit commented on tests/trestle/core/commands/import__test.py
> +                AssertionError()
Simplified to checking for the return code.

2020-12-08 06:01 UTC, jeffdmgit commented on tests/trestle/core/commands/import__test.py
> +            AssertionError()
Done.

2020-12-08 06:03 UTC, jeffdmgit commented on trestle/core/commands/import_.py
> +        # 7. Leave the rest to trestle split
Not yet, at least not beyond splitting down one level, from my testing. Best to leave it until split can definitely process deeper down element level paths

2020-12-08 06:27 UTC, jeffdmgit commented on tests/trestle/core/commands/import__test.py
> +            assert rc == 1
Added the test with an attempt to import `groups`, but the response from *parser.parse_file()* isn't entirely specific. It just says 'model_name is required'. This is the same response if one attempts to import valid json with a key that isn't a valid element at all, e.g., _{ "id": "000" }_. If there a need to distinguish, then it has to be done from _parser.parse_file()_.

2020-12-08 06:33 UTC, butler54 commented on tests/trestle/core/commands/import__test.py
> +            assert rc == 1
Yes I agree.

2020-12-08 06:40 UTC, butler54 commented on tests/trestle/core/commands/import__test.py
> +            assert rc == 1
So I think there are two usescases.

The first is testing 'did the class actually receive all the mandatory arguments. E.g. we are testing whether we are getting the expected behaviour from ilcli and argparse. This should be done with Trestle.run().

For testing for a specific behaviour for the unit test we should be testing as tight as possible in terms of the unit test. This means we have clarity that nothing is capturing exceptions where we dont expect (say for example in ILCLI).

See as an example this create command test below (it does not call `_run` for some esoteric reasons, however, the  example holds true.

```python
def test_fail_overwrite(tmp_trestle_dir: pathlib.Path) -> None:
    """Test that a failure occurs when doubling up a create."""
    args = argparse.Namespace(extension='json', name='my_catalog', verbose=0)
    rc = create.CreateCmd.create_object('catalog', Catalog, args)
    assert rc == 0
    rc = create.CreateCmd.create_object('catalog', Catalog, args)
    assert rc > 0

```

2020-12-08 06:40 UTC, butler54 commented on tests/trestle/core/commands/import__test.py
> +    }
@jeffdmgit you missed this:?

2020-12-08 06:41 UTC, butler54 requested changes
See the unclosed comments. I think there is a little way to go but it's close.

2020-12-08 12:58 UTC, jeffdmgit commented on tests/trestle/core/commands/import__test.py
> +            assert rc == 1
Done! I retained the happy path test calling Trestle().run() while the rest call _run() on an instance.

2020-12-09 21:30 UTC, jeffdmgit commented
> See the unclosed comments. I think there is a little way to go but it's close.

Please review again.

2020-12-09 23:37 UTC, fsuits approved these changes
LGTM

2020-12-10 00:58 UTC, jeffdmgit reviewed
I used generators except in cases where I needed to attempt an import of invalid data.

2020-12-10 00:59 UTC, jeffdmgit commented on tests/trestle/core/commands/import__test.py
> +    }
Already done.

2020-12-10 03:45 UTC, butler54 approved these changes
LGTM

2020-12-10 03:46 UTC, merged