Autoformat GFM tables with mdformat-gfm
IBM/compliance-trestle pull request #268
Opened 2020-12-17 03:10 UTC by hukkinj1

Thought you might find the mdformat-gfm plugin useful. It changes Markdown spec from Commonmark to GFM, so tables, for instance, are formatted. No longer need to manually make whitespace align :smile:

2020-12-18 02:12 UTC, butler54 requested changes
This LGTM from a code change point of view. A small request could you please ensure either
a) Your code is signed off with --signoff or
b) Add an explicit signoff of the DCO in the PR comments
that would be fantastic.

Thanks!

2020-12-18 09:27 UTC, hukkinj1 commented
:+1: Redid the commit with `--signoff`

2020-12-20 22:01 UTC, butler54 approved these changes
LGTM

2020-12-20 22:01 UTC, butler54 commented
Thanks again much appreciated!

2020-12-20 22:02 UTC, merged