DRAFT: Added Repo APIs and set trestle root in main command
IBM/compliance-trestle pull request #583
Opened 2021-06-23 04:37 UTC by vikas-agarwal76

## Types of changes

- \[ \] Bug fix (non-breaking change which fixes an issue)
- \[X \] New feature (non-breaking change which adds functionality)
- \[X \] Breaking change (fix or feature that would cause existing functionality to change)
- \[X \] My code follows the code style of this project.
- \[X \] My change requires a change to the documentation.
- \[ \] I have updated the documentation accordingly.
- \[ \] I have added tests to cover my changes.
- \[ \] All new and existing tests passed.
- \[ \] All commits are signed-off.

Added API for main Repository class. API implementation for ManagedOSCAL is still pending. Added trestle_root args in the base command and its default value is set to Path.cwd().

2021-06-24 06:10 UTC, butler54 commented
@vikas-agarwal76 - can you update to the latest version in develop and then I can have a look?

2021-06-24 06:31 UTC, vikas-agarwal76 commented
@butler54 Updated latest from develop

2021-07-02 07:02 UTC, butler54 commented
Looking good so far. Please remove the commented out code.

2021-07-07 12:50 UTC, vikas-agarwal76 commented
@butler54 Pushed final changes to feat/repo. Please check. Also I see some tests failing. Pls. check that also.

2021-07-12 07:42 UTC, vikas-agarwal76 commented
@butler54 I have merged the latest from develop and the changes to test cases to handle trestle_root. Pls. review and merge into develop.

2021-07-12 22:07 UTC, butler54 requested changes
See the changes requested:
One is structural (location of files)
Many are commented out code.

2021-07-13 04:31 UTC, vikas-agarwal76 commented on trestle/utils/fs.py
>  def get_contextual_model_type(path: pathlib.Path = None) -> Tuple[Type[OscalBaseModel], str]:
Even if the user is providing a path then the check 
if not path.exists():
            path = pathlib.Path.cwd() / path

still needs to be there of check is path is valid. 

So we can leave the code as it is.

2021-07-13 04:31 UTC, vikas-agarwal76 commented on trestle/core/commands/assemble.py
> +        # comment    return 1
Done

2021-07-13 04:31 UTC, vikas-agarwal76 commented on trestle/core/commands/assemble.py
> +            # comment logger.error(f'Current working directory {Path.cwd()} is not with a trestle project.')
done

2021-07-13 04:31 UTC, vikas-agarwal76 commented on trestle/core/commands/import_.py
> +        # comment trestle_root = fs.get_trestle_project_root(cwd)
done

2021-07-13 04:31 UTC, vikas-agarwal76 commented on trestle/core/commands/init.py
> +        # comment dir_path = os.getcwd()
done

2021-07-13 04:32 UTC, vikas-agarwal76 commented on trestle/core/commands/replicate.py
> +        # comment trestle_root = fs.get_trestle_project_root(cwd)
done

2021-07-13 04:32 UTC, vikas-agarwal76 commented on trestle/core/commands/repo/trestle_repo.py
> +# Copyright (c) 2020 IBM Corp. All rights reserved.
done

2021-07-13 04:32 UTC, vikas-agarwal76 commented on trestle/core/commands/task.py
> +        # comment trestle_root = fs.get_trestle_project_root(pathlib.Path.cwd())
done

2021-07-13 04:32 UTC, vikas-agarwal76 commented on trestle/utils/fs.py
> +    # FIXME: set default value of path to Path.cwd()
done

2021-07-13 04:33 UTC, vikas-agarwal76 commented on trestle/utils/fs.py
> +    # comment trestle_root = get_trestle_project_root(pathlib.Path.cwd())
done

2021-07-13 04:44 UTC, vikas-agarwal76 commented on trestle/core/commands/repo/trestle_repo.py
> +        """Initialize trestle epository object."""
done

2021-07-13 05:22 UTC, vikas-agarwal76 commented on trestle/core/commands/repo/trestle_repo.py
> +        plural_path = fs.model_type_to_model_dir(model_alias)
Done.

2021-07-13 05:45 UTC, vikas-agarwal76 commented on trestle/core/commands/repo/__init__.py
> +# -*- mode:python; coding:utf-8 -*-
done. moved trestle_repo.py to trestle/core/repository.py

2021-07-13 05:45 UTC, vikas-agarwal76 commented on trestle/core/commands/repo/trestle_repo.py
> +# -*- mode:python; coding:utf-8 -*-
done. moved trestle_repo.py to trestle/core/repository.py

2021-07-13 05:50 UTC, vikas-agarwal76 commented
@butler54 Made all the changes suggested by you. See my reply to you individual comments. Also moved the trestle_repo.py to trestle/core/repository.py

2021-07-13 05:51 UTC, vikas-agarwal76 commented on trestle/core/commands/repo/trestle_repo.py
> +        plural_path = fs.model_type_to_model_dir(model_alias)
Applied type checking to all relevant functions.

2021-07-13 07:57 UTC, butler54 approved these changes
LGTM

2021-07-13 07:57 UTC, butler54 commented on trestle/utils/fs.py
>  def get_contextual_model_type(path: pathlib.Path = None) -> Tuple[Type[OscalBaseModel], str]:
Okay awesome.

2021-07-13 07:57 UTC, butler54 commented on trestle/utils/fs.py
> +    # FIXME: set default value of path to Path.cwd()
I think this is not a fixme. (I'll edit it quickly).

2021-07-13 08:10 UTC, merged